spring.application.name=sistema-chamados-java

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/chamados_db}
spring.datasource.username=${DB_USER:chamados_app}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false