CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_usuarios_email UNIQUE (email),

    CONSTRAINT ck_usuarios_nome_nao_vazio
        CHECK (CHAR_LENGTH(TRIM(nome)) > 0),

    CONSTRAINT ck_usuarios_email_nao_vazio
        CHECK (CHAR_LENGTH(TRIM(email)) > 0),

    CONSTRAINT ck_usuarios_email_normalizado
        CHECK (email = LOWER(TRIM(email))),

    CONSTRAINT ck_usuarios_senha_hash_nao_vazio
        CHECK (CHAR_LENGTH(TRIM(senha_hash)) > 0)
);